sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ssvishal1990/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ssvishal1990/docker-react npm run test -- --coverage 
